### ISSUE TITLE
Use new clj-loga library for JSON logging goodness!

### ISSUE THREAD

**Issue by rsslldnphy** [FundingCircle/clj-loga#11]
:dancer::dancer::dancer: Hello from the Janus "non-functional" team! :dancer::dancer::dancer:

We're a new team set up to tackle cross-cutting concerns such as logging, monitoring and alerting, and end-to-end testing. We'll be building tools to help make these things easier, but it's not just about code: we'll also be helping teams adopt consistent approaches across the board.

And we'll sometimes create issues on your repos, like this one. We're not just dropping work in your lap, though. Give any one of us a shout and we'll pair with you on implementing whatever changes are required.

First up is logging. We now have a cool new library, [clj-loga](http://github.com/fundingcircle/clj-loga), written by @apmaros and @timstott, that makes it easy for you to use JSON logging in your apps. This means that logs in Kibana will start to become a bit more meaningful - and searchable - like this:

![kibana-with-clj-loga](https://cloud.githubusercontent.com/assets/1231200/12167559/cfe03fe0-b524-11e5-981b-ce952654a3bc.png)

This is how @apmaros describes `clj-loga`:

> We have worked on improving quality and usability of searching and filtering logs. Its result is library `clj-loga` which help us to log easier and filter faster by:
> * JSON format - allows easily parse and add new tags
> * New tag - namespace and more to come
> * User can set a 'tag' - to filter it specifically instead of regexing it from message
> * Wrap number of functions (with a common purpose) with loggs - This is useful for operations such as 'Processing xyz kafka message'. Cleaner functions.
> * Removing all noise from the log @message
> * Support for stacktrace - not encouraged, but stacktrace is logged as a single log event.

## What you need to do

To use `clj-loga`, you will need to be using `timbre` >= 4.1.1. There is also a small amount of setup code you'll need in your app, described in the `clj-loga` readme. If you'd like to pair on setting it up in one of your apps, grab either @apmaros or @rsslldnphy, who will be happy to work with you on it. Any questions let us know!

**Comment by apmaros** [comment]
Closing issue for too much goodness :dancer:
