### ISSUE TITLE
Obfuscate sensitive information

### ISSUE THREAD

**Issue by nachomdo** [FundingCircle/clj-loga#12]
Sometimes logs are a source of sensitive information leaks. In an event-driven architecture, it's common to log processed events messages that usually are represented as maps in Clojure. 

Maybe we could add an option to whitelist which fields contain sensitive data and obfuscate them in production logs. So the production log output for a message with a whitelisted :c field would be:

```
;; {"timestamp":"2015-12-31T11:19:28.146Z","level":"INFO","message":"started: processing message {:a 1 :b 2 :c XXXX :d 4}","namespace":"clj-loga.core","tag":"some-tag"}
```

**Comment by stuart-robinson** [comment]
:+1:

**Comment by apmaros** [comment]
:+1:
