### ISSUE TITLE
Specify log level via environment variable

### ISSUE THREAD

**Issue by timstott** [FundingCircle/clj-loga#17]
We are lacking the ability to set the log level via env when running the application.
Timbre only makes use of the `TIMBRE_LEVEL` env at [compile time](https://github.com/ptaoussanis/timbre/tree/ce86c16277ac43504b424e1a9166340834b52ca0#log-levels-and-ns-filters).

Perhaps we could introduce the following env:

```
LOGA_LEVEL=:debug
```

:bulb: should levels be specified as strings `debug` or keyword `:debug`?

**Comment by broi-fc** [comment]
At the  moment any application that requires it can add it in its code:

    (setup-loga :level (keyword (:loga-level env "info")))

However I think it would be nice to make this be default.

**Comment by apmaros** [comment]
Do we have any use case at the moment for this feature? By default we are mainly interested in `info` level only, which is setup by default.

**Comment by timstott** [comment]
I believe we do. Once apps are deployed we have no way to change the log level without a code change, which terribly annoying when debugging.

**Comment by apmaros** [comment]
as Stan mentioned, `(setup-loga :level (keyword (:loga-level env "info")))` allows dynamically set the level. closing issue
