### ISSUE TITLE
ENABLE_LOGA doesn't seem to exist

### ISSUE THREAD

**Issue by whamilton42** [FundingCircle/clj-loga#18]
The readme says:

```bash
#export env variable to apply formatting
ENABLE_LOGA=true
```

But that environment variable is [never used](https://github.com/FundingCircle/clj-loga/search?utf8=%E2%9C%93&q=ENABLE_LOGA). What's up?

**Comment by fussybeaver** [comment]
I think it's being used here https://github.com/FundingCircle/clj-loga/blob/e2641bb7533cb29f3a24ac549ced8e14a42598fb/src/clj_loga/core.clj#L90

**Comment by apmaros** [comment]
Yes, its being used with (environ)[https://github.com/weavejester/environ] as `(env :enable-loga)` where @fussybeaver pointed out.

**Comment by whamilton42** [comment]
Ah - undone by hyphens/underscores again.
