### ISSUE TITLE
Exception message and `ExceptionInfo`'s metadata should be logged

### ISSUE THREAD

**Issue by ponzao** [FundingCircle/clj-loga#21]
With the newest version of clj-loga (0.5.0) we seem to lose the exception's original message, example:

```
(timbre/error (Exception. "BOOM") "Something bad happened")
;=>
{"timestamp":"2016-04-22T13:21:20.580Z","level":"ERROR","message":"Something bad happened","namespace":"gocardless-reconciler.core","stacktrace":"gocardless_reconciler.core$eval25772$fn__25773.invoke(core.clj:29)\n...
```

(Result clipped)

In addition if the type of the exception is a `clojure.lang.ExceptionInfo` we lose the map that is stored in the object, example:

```
(timbre/error (ex-info "BOOM" {:foo :bar}) "Something bad happened")
;=>
{"timestamp":"2016-04-22T13:23:55.040Z","level":"ERROR","message":"Something bad happened","namespace":"gocardless-reconciler.core","stacktrace":"clojure.core$ex_info.invokeStatic(c...
```

(Result clipped)

**Comment by whamilton42** [comment]
Worth noting that we're not sure if this is a regression, or if this has never worked.

**Comment by apmaros** [comment]
@ponzao looking into it now

**Comment by apmaros** [comment]
The error is most likely cause when formatting the serialization the stacktrace to json. ex-info contain additional information to the exception which is not being picked up.
