### ISSUE TITLE
Use of `env` in top level `def` will break under some circumstances.

### ISSUE THREAD

**Issue by rsslldnphy** [FundingCircle/clj-loga#5]
The use of environ's `env` here: https://github.com/FundingCircle/clj-loga/blob/master/src/clj_loga/core.clj#L86 will break in some circumstances (if I remember correctly, either when the code is compiled into a jar, or when AOT compilation is used).

```clojure
(def ^:private loga-enabled?
  (= (env :enable-loga) "true"))
```

This is because the `def` is calculated at compile-time rather than run-time. And at compile time, the environment variables won't be set. 

When running with leiningen (i.e. in development), the environment variables *will* be set at compile time, so the problem won't manifest until we push it to an environment.

Easy fix is to make this a function rather than a `def`.

**Comment by apmaros** [comment]
You are right, thanks!

**Comment by rsslldnphy** [comment]
Closing this as the fix has been merged!
